%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Plot vertical transect using the .mat file generated by Scott's mfile
%
% J. Jung
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear; clc; close all

vari_str = 'salt';
yyyy_all = 2019:2022;
% plusind = yyyy_all(1) - 2015;
plusind = 0;
mm = 8;
mstr = num2str(mm, '%02i');

% region = 'Gulf_of_Anadyr_NW_SE';
% region = 'Cape_Navarin';
region = 'Gulf_of_Anadyr_NW_SE'; lon_entrance = -176.9945; lat_entrance = 63.3551;

switch vari_str
    case 'salt'
        color = 'jet';
        climit = [29 34];
        contour_interval = climit(1):.5:climit(2);
        unit = 'psu';
        titlestr = 'salinity';
        savename = 'vertical_salt';
    case 'temp'
        color = 'parula';
        climit = [-2 12];
        contour_interval = climit(1):2:climit(2);
        unit = '^oC';
        titlestr = 'temperature';
        savename = 'vertical_temp';
    case 'pden'
        color = 'parula';
        climit = [24 27];
        contour_interval = climit(1):.3:climit(end);
        unit = '\sigma_t';
        titlestr = 'density';
        savename = 'vertical_pden';
    case 'v_n'
        color = 'redblue';
        climit = [-20 20];
        contour_interval = climit(1):5:climit(2);
        unit = 'cm/s';
        titlestr = 'normal velocity';
        savename = 'vertical_v_n';
    case 'u_t'
        color = 'redblue';
        climit = [-20 20];
        contour_interval = climit(1):5:climit(2);
        unit = 'cm/s';
        titlestr = 'tangential velocity';
        savename = 'vertical_u_t';
    case 'w'
        color = 'redblue';
        climit = [-1e-4 1e-4];
        contour_interval = [-1e-4 1e-4];
        unit = 'm/s';
        titlestr = 'Vertical velocity';
        savename = 'vertical_w';
end

switch region
    case 'Cape_Navarin'
        text1_dep = -150;
        text1_lon = -181;
        text2_dep = -185;
        text2_lon = -181;
        text_FS = 20;
    case 'Gulf_of_Anadyr_NW_SE'
        text1_dep = -70;
        text1_lon = -180;
        text2_dep = -85;
        text2_lon = -180;
        text_FS = 20;
    case 'Anadyr_Strait'
        text1_dep = -40;
        text1_lon = -173;
        text2_dep = -50;
        text2_lon = -173;
        text_FS = 20;
        if strcmp(vari_str, 'v_n')
            climit = [-50 50];
            contour_interval = climit(1):10:climit(2);
        end
    case 'Navarin_Matthew'
        text1_dep = -97;
        text1_lon = -175;
        text2_dep = -115;
        text2_lon = -175;
        text_FS = 20;
end
title_str = strrep(region, '_' , ' ');

figure;
% set(gcf, 'Position', [1 200 1400 900])
set(gcf, 'Position', [1 200 500 350])
% Figure title
title(['ROMS climate ', titlestr, ' (', title_str, ')'], 'FontSize', 15);

temp_sum = zeros;
salt_sum = zeros;
v_n_sum = zeros;
for yi = 1:length(yyyy_all)
    yyyy = yyyy_all(yi); ystr = num2str(yyyy);
    title_str = datestr(datenum(yyyy,mm,1), 'mmm, yyyy');

    load([region, '_transect_ocean_vars_', ystr, '_monthly.mat']);

    mask = Seg.mask;
    depth = Seg.zseca;
    lon = Seg.lonseca;
    lat = Seg.latseca;

    temp_tmp = Sec.temp(:,:,mm);
    salt_tmp = Sec.salt(:,:,mm);
    v_n_tmp = Sec.v_n(:,:,mm);

    temp_sum = temp_sum + temp_tmp;
    salt_sum = salt_sum + salt_tmp;
    v_n_sum = v_n_sum + v_n_tmp;
end
temp = temp_sum/length(yyyy_all);
salt = salt_sum/length(yyyy_all);
v_n = v_n_sum/length(yyyy_all);

if strcmp(vari_str, 'v_n') || strcmp(vari_str, 'u_t')
    vari = eval([vari_str]);
    vari = vari.*100;
elseif strcmp(vari_str, 'pden')
    pres = sw_pres(depth, lat);
    pden = sw_pden_ROMS(salt, temp, pres, 0);
    vari = pden - 1000;
else
    vari = eval(vari_str);
end

% Tile
nexttile(yi+plusind); hold on;
pcolor(lon, depth, vari.*mask); shading flat
[cs,h] = contour(lon, depth, vari.*mask, [contour_interval], 'k');
clabel(cs, h, 'Color', 'k', 'FontSize', 15)
caxis(climit)
if strcmp(region, 'Gulf_of_Anadyr_NW_SE')
    xlim([min(min(lon)) lon_entrance]);
end

colormap(color)

xlabel('Longitude')
ylabel('Depth (m)')

c = colorbar;
c.Layout.Tile = 'east';
c.Title.String = unit;
c.FontSize = 15;

set(gca, 'FontSize', 15)

%     text(-181, -180, [title_str], 'FontSize', 20)
text(text1_lon, text1_dep, datestr(datenum(yyyy,mm,1), 'mmm'), 'FontSize', text_FS)
text(text2_lon, text2_dep, datestr(datenum(yyyy,mm,1), 'yyyy'), 'FontSize', text_FS)

pause(3)

print([savename, '_', region, '_climate_', mstr],'-dpng');

vari_climate = vari;
save([vari_str, '_', region, '_climate_', mstr, '.mat'], 'vari_climate')