%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Plot timeseries along the transect using the .mat file generated by Scott's mfile
%
% J. Jung
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear; clc; close all

yyyy_all = 2019:2023;
% plusind = yyyy_all(1) - 2015;
mm_all = 1:12;

vari = 'str_n';
lon_ind = -178;

region = 'Cape_Navarin';
title_str = strrep(region, '_', ' ');

g = grd('BSf');

for yi = 1:length(yyyy_all)
    yyyy = yyyy_all(yi); ystr = num2str(yyyy);

    for mi = 1:length(mm_all)
        mm = mm_all(mi); mstr = num2str(mm, '%02i');

        title_str = datestr(datenum(yyyy,mm,1), 'mmm, yyyy');

        load([region, '_transect_ocean_vars_', ystr, '_monthly.mat']);

        timenum = timeR;
        mask = Seg.mask;
        mask2d = Seg.mask2d;
        azimuth = Seg.azimuth;
        depth = Seg.zseca;
        h = Seg.depth;
        lon = Seg.lonseca;
        lat = Seg.latseca;
        azimuth = Seg.azimuth;

        ds = Seg.ds; % km
        ds = ds.*1000; % m
        ds_2d = repmat(ds', [1, g.N]);

        try 
            zeta = Sec.zeta(:,mm);
            aice = Sec.aice(:,mm);
            sustr = Sec.sustr(:,mm);
            svstr = Sec.svstr(:,mm);
            salt = Sec.salt(:,:,mm);
            v_n = Sec.v_n(:,:,mm);
        catch
            zeta = NaN;
            aice = NaN;
            sustr = NaN;
            svstr = NaN;
            salt = NaN;
            v_n = NaN;
        end

        str_n = sind(azimuth)'.*sustr  ...
            - cosd(azimuth)'.*svstr;
        str_t = -cosd(azimuth)'.*sustr  ...
            - sind(azimuth)'.*svstr;


%         index = find(lon(:,1) < lon_ind);

%         SSS_mean(yi,mi) = mean(salt(:,g.N), 'omitnan');
%         v_n_mean(yi,mi) = mean(v_n(:,g.N), 'omitnan');
        str_t_mean(yi,mi) = mean(str_t(:), 'omitnan');
        str_n_mean(yi,mi) = mean(str_n(:), 'omitnan');
    end
end % yi

figure; hold on; grid on;
set(gcf, 'Position', [1 200 800 500])
for yi = 1:length(yyyy_all)
    plot(mm_all, str_t_mean(yi,:), '-o', 'LineWidth', 2)
end
ddd
print(['v_n_mean_', region, '_', num2str(lon_ind)],'-dpng');