%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Plot transect of 2D variables using the .mat file generated by Scott's mfile
%
% J. Jung
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear; clc; close all

yyyy_all = 2019:2023;
% plusind = yyyy_all(1) - 2015;
plusind = 0;
mm = 7;
mstr = num2str(mm, '%02i');

region = 'Koryak_coast';
title_str = strrep(region, '_', ' ');

ylimit1 = [-30 30];
ylimit2 = [-1.5 1.5];
savename = 'zeta_w_str_n';

switch region
    case 'Cape_Navarin'
        lon_limit = [-180.7];
    case 'Gulf_of_Anadyr'
    case 'Koryak_coast'
        lon_limit = [-183];
    case 'Anadyr_Strait'
        ylimit = [-40 40];
    case 'Navarin_Matthew'
        lon_limit = -178;
end

figure;
% set(gcf, 'Position', [1 200 1400 900])
set(gcf, 'Position', [1 200 1500 300])
t = tiledlayout(1,5);
% Figure title
title(t, ['ROMS zeta and surface normal stress (', title_str, ')'], 'FontSize', 15);

for yi = 1:length(yyyy_all)
    yyyy = yyyy_all(yi); ystr = num2str(yyyy);
    title_str = datestr(datenum(yyyy,mm,1), 'mmm, yyyy');

    load([region, '_transect_ocean_vars_', ystr, '_monthly.mat']);

    timenum = timeR;
    mask = Seg.mask;
    mask2d = Seg.mask2d;
    azimuth = Seg.azimuth;
    depth = Seg.zseca;
    lon = Seg.lonseca;
    lat = Seg.latseca;
    azimuth = Seg.azimuth;

    zeta = Sec.zeta(:,mm);
    aice = Sec.aice(:,mm);
    sustr = Sec.sustr(:,mm);
    svstr = Sec.svstr(:,mm);

    str_n = sind(azimuth)'.*sustr  ...
        - cosd(azimuth)'.*svstr;
    str_t = -cosd(azimuth)'.*sustr  ...
        - sind(azimuth)'.*svstr;

    % Tile
    nexttile(yi+plusind); hold on; grid on
    p1 = plot(lon, zeta*100, '-k', 'LineWidth', 2);
    if strcmp(region, 'Gulf_of_Anadyr_NW_SE')
        xlim([min(min(lon)) lon_limit]);
    elseif strcmp(region, 'Navarin_Matthew')
        xlim([min(min(lon)) lon_limit]);
    else
        xlim([min(min(lon)) max(max(lon))])
    end
    ylim(ylimit1)

    xlabel('Longitude')
    ylabel('zeta (cm)')

    yyaxis right
    p2 = plot(lon, str_n, '-b', 'LineWidth', 2);
    ylim(ylimit2)
    ylabel('Surface normal stress (N/m^2)')
    
    ax = gca;
    ax.YColor = 'b';

    set(gca, 'FontSize', 10)

    title([title_str], 'FontSize', 12)
end % yi

t.Padding = 'compact';
t.TileSpacing = 'compact';

print([savename, '_', region, '_', mstr],'-dpng');

% figure; hold on;
% plot_map('Bering', 'mercator', 'l')
% set(gcf, 'Position', [1 200 800 500])
% contourm(g.lat_rho, g.lon_rho, g.h, [50 100 200], 'k')
% plotm(lat, lon, '-r', 'LineWidth', 4)
% print(['transect_', region], '-dpng')