%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Plot vertical transect using the .mat file generated by Scott's mfile
%
% J. Jung
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear; clc; close all

vari_str = 'salt';
yyyy_all = 2019:2022;
% plusind = yyyy_all(1) - 2015;
plusind = 0;
mm = 8;
mstr = num2str(mm, '%02i');

% region = 'Gulf_of_Anadyr_NW_SE';
% region = 'Cape_Navarin';
region = 'Gulf_of_Anadyr_NW_SE'; lon_entrance = -176.9945; lat_entrance = 63.3551;

switch vari_str
    case 'salt'
        color = 'redblue';
        climit = [-2 2];
        contour_interval = climit(1):.5:climit(2);
        unit = 'psu';
        titlestr = 'salinity';
        savename = 'vertical_salt';
    case 'temp'
        color = 'parula';
        climit = [-2 12];
        contour_interval = climit(1):2:climit(2);
        unit = '^oC';
        titlestr = 'temperature';
        savename = 'vertical_temp';
    case 'pden'
        color = 'parula';
        climit = [24 27];
        contour_interval = climit(1):.3:climit(end);
        unit = '\sigma_t';
        titlestr = 'density';
        savename = 'vertical_pden';
    case 'v_n'
        color = 'redblue';
        climit = [-20 20];
        contour_interval = climit(1):5:climit(2);
        unit = 'cm/s';
        titlestr = 'normal velocity';
        savename = 'vertical_v_n';
    case 'u_t'
        color = 'redblue';
        climit = [-20 20];
        contour_interval = climit(1):5:climit(2);
        unit = 'cm/s';
        titlestr = 'tangential velocity';
        savename = 'vertical_u_t';
    case 'w'
        color = 'redblue';
        climit = [-1e-4 1e-4];
        contour_interval = [-1e-4 1e-4];
        unit = 'm/s';
        titlestr = 'Vertical velocity';
        savename = 'vertical_w';
end

switch region
    case 'Cape_Navarin'
        text1_dep = -150;
        text1_lon = -181;
        text2_dep = -185;
        text2_lon = -181;
        text_FS = 20;
    case 'Gulf_of_Anadyr_NW_SE'
        text1_dep = -70;
        text1_lon = -180;
        text2_dep = -85;
        text2_lon = -180;
        text_FS = 20;
    case 'Anadyr_Strait'
        text1_dep = -40;
        text1_lon = -173;
        text2_dep = -50;
        text2_lon = -173;
        text_FS = 20;
        if strcmp(vari_str, 'v_n')
            climit = [-50 50];
            contour_interval = climit(1):10:climit(2);
        end
    case 'Navarin_Matthew'
        text1_dep = -97;
        text1_lon = -175;
        text2_dep = -115;
        text2_lon = -175;
        text_FS = 20;
end
title_str = strrep(region, '_' , ' ');

figure;
% set(gcf, 'Position', [1 200 1400 900])
set(gcf, 'Position', [1 200 1500 300])
t = tiledlayout(1,4);
% Figure title
title(t, ['ROMS ', titlestr, ' (', title_str, ')'], 'FontSize', 15);

for yi = 1:length(yyyy_all)
    yyyy = yyyy_all(yi); ystr = num2str(yyyy);
    title_str = datestr(datenum(yyyy,mm,1), 'mmm, yyyy');

    load([region, '_transect_ocean_vars_', ystr, '_monthly.mat']);

    timenum = timeR;
    mask = Seg.mask;
    mask2d = Seg.mask2d;
    azimuth = Seg.azimuth;
    depth = Seg.zseca;
    lon = Seg.lonseca;
    lat = Seg.latseca;

    temp = Sec.temp(:,:,mm);
    salt = Sec.salt(:,:,mm);
    v_n = Sec.v_n(:,:,mm);
    u_t = Sec.u_t(:,:,mm);
    w = Sec.w(:,:,mm);
    zeta = Sec.zeta(:,mm);
    aice = Sec.aice(:,mm);
    sustr = Sec.sustr(:,mm);
    svstr = Sec.svstr(:,mm);

    if strcmp(vari_str, 'v_n') || strcmp(vari_str, 'u_t')
        vari = eval(vari_str);
        vari = vari.*100;
    elseif strcmp(vari_str, 'pden')
        pres = sw_pres(depth, lat);
        pden = sw_pden_ROMS(salt, temp, pres, 0);
        vari = pden - 1000;
    else
        vari = eval(vari_str);
    end

    load(['salt_', region, '_climate_', mstr, '.mat'])
    vari = vari - vari_climate;

    % Tile
    nexttile(yi+plusind); hold on;
    pcolor(lon, depth, vari.*mask); shading flat
    [cs,h] = contour(lon, depth, vari.*mask, [contour_interval], 'k');
    clabel(cs, h, 'Color', 'k', 'FontSize', 15)
    caxis(climit)
    if strcmp(region, 'Gulf_of_Anadyr_NW_SE')
        xlim([min(min(lon)) lon_entrance]);
    end

    colormap(color)

    xlabel('Longitude')
    ylabel('Depth (m)')

    if yi == 1
        c = colorbar;
        c.Layout.Tile = 'east';
        c.Title.String = unit;
        c.FontSize = 15;
    end

    set(gca, 'FontSize', 15)

    %     text(-181, -180, [title_str], 'FontSize', 20)
    text(text1_lon, text1_dep, datestr(datenum(yyyy,mm,1), 'mmm'), 'FontSize', text_FS)
    text(text2_lon, text2_dep, datestr(datenum(yyyy,mm,1), 'yyyy'), 'FontSize', text_FS)

end % yi

t.Padding = 'compact';
t.TileSpacing = 'compact';

pause(3)

print([savename, '_anomaly_', region, '_', mstr],'-dpng');

% figure; hold on;
% g = grd('BSf');
% plot_map('Gulf_of_Anadyr', 'mercator', 'l')
% set(gcf, 'Position', [1 200 800 500])
% contourm(g.lat_rho, g.lon_rho, g.h, [50 100 200], 'k')
% if strcmp(region, 'Gulf_of_Anadyr_NW_SE')
%     lon_1d = lon(:,1);
%     dist = abs(lon_1d - lon_entrance);
%     index = find(dist == min(dist));
%     lon = lon(1:index,:);
%     lat = lat(1:index,:);
% end
% plotm(lat, lon, '-r', 'LineWidth', 4)
% print(['transect_', region], '-dpng')