%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Calculated transport using the .mat file generated by Scott's mfile
%
% J. Jung
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear; clc

yyyy = 2020; ystr = num2str(yyyy);
regions = {'Anadyr_Strait', 'Cape_Navarin', 'Line1'};

trans = [];
for ri = 1:length(regions)

    region = regions{ri};

    load([region, '_transect_ocean_vars_', ystr, '.mat']);

    timenum = timeR;
    mask = Seg.mask;
    mask2d = Seg.mask2d;
    azimuth = Seg.azimuth;

    z_w = Seg.zsecaw;
    dz = z_w(:,2:end) - z_w(:,1:end-1);

    ds = Seg.ds; % km
    ds = ds.*1000; % m
    ds_2d = repmat(ds', [1, 45]);

    v_n = Sec.v_n;
    u_t = Sec.u_t;
    zeta = Sec.zeta;
    sustr = Sec.sustr;
    svstr = Sec.svstr;

    for ti = 1:length(timenum)

        % Transport
        v_n_tmp = v_n(:,:,ti);
        v_times_area =  v_n_tmp.*dz.*ds_2d.*mask;
        trans(ri, ti) = sum(v_times_area(:), 'omitnan');
    end
end

figure; hold on; grid on
for ri = 1:length(regions)
    plot(timenum, trans(ri,:));
end
xticks(timenum)
datetick('x', 'mmm dd', 'keepticks', 'keeplimits')
d
save(['trans_', ystr, '.mat'], 'trans')